"""Render the idempotent Rails-runner admin script from a Model.

Standard library only. The script uses `find_or_initialize_by` everywhere and
prints one line per created or changed record (nothing for unchanged ones).
The only destructive call is the workflow reset, scoped to the exact
(role, type) pair it manages.
"""

from __future__ import annotations


def rb(value):
    """Render a Ruby single-quoted string literal (only \\ and \\' escape)."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def rb_dq(value):
    """Render a Ruby double-quoted literal; #{...} interpolates."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _section(out, title):
    out.append("")
    out.append("# --- %s ---" % title)


def render_admin_script(model):
    """Return the full admin script for `bundle exec rails runner`."""
    out = [
        "# Generated by opl-configure from config/pm-model.toml. Idempotent:",
        "# safe to run on every configure. Prints created/changed records only.",
        "",
        "def opl_report(label, record)",
        "  if record.previous_changes.any?",
        '    puts "#{label}: created or changed '
        "(#{record.previous_changes.keys.join(\", \")})\"",
        "  end",
        "end",
    ]

    by_type = {t.name: t for t in model.types}

    # 1. Statuses: find or create, then set closed/% done/default.
    # is_default is pinned from the model's global_default (T1.3 review).
    _section(out, "Statuses")
    default_name = model.global_default if model.global_default else "Draft"
    for s in model.statuses:
        out.append("s = Status.find_or_initialize_by(name: %s)" % rb(s.name))
        out.append(
            "s.assign_attributes(is_closed: %s, default_done_ratio: %d, "
            "is_default: %s)"
            % ("true" if s.closed else "false", s.done_ratio,
               "true" if s.name == default_name else "false")
        )
        out.append("if s.new_record? || s.changed?")
        out.append("  s.save!")
        out.append("  opl_report(%s, s)" % rb("status " + s.name))
        out.append("end")

    # 2. Types: find or create, then enable in every project.
    _section(out, "Types")
    for t in model.types:
        out.append("t = Type.find_or_initialize_by(name: %s)" % rb(t.name))
        out.append("if t.new_record?")
        out.append("  t.save!")
        out.append("  opl_report(%s, t)" % rb("type " + t.name))
        out.append("end")
        out.append("Project.find_each do |project|")
        out.append("  pt = ProjectType.find_or_initialize_by(project: project, type: t)")
        out.append("  if pt.new_record?")
        out.append("    pt.save!")
        out.append(
            "    puts %s" % rb_dq("type %s: enabled in project #{project.name}" % t.name)
        )
        out.append("  end")
        out.append("end")

    # 3. Roles: project roles with the exact permission set. "all" resolves
    # the non-global permissions from the registry at run time (verified
    # against lib/open_project/access_control.rb + permission.rb @ v17.8.0:
    # permissions.reject(&:global?).map(&:name), permission(name) nil-check).
    # Unknown explicit names raise instead of silently creating dead rows.
    _section(out, "Roles")
    for r in model.roles:
        out.append(
            "r = Role.find_or_initialize_by(name: %s, type: 'ProjectRole')"
            % rb(r.name)
        )
        if r.permissions == "all":
            out.append("wanted = OpenProject::AccessControl.permissions.reject(&:global?).map(&:name)")
            out.append('raise "no project permissions found in registry" if wanted.empty?')
        else:
            out.append("names = %s" % _rb_str_list(r.permissions))
            out.append("names.each do |pname|")
            out.append(
                "  raise \"unknown permission #{pname} in role %s\" "
                "if OpenProject::AccessControl.permission(pname.to_sym).nil?" % r.name
            )
            out.append("end")
            out.append("wanted = names.map(&:to_sym)")
        out.append("before = r.permissions.map(&:to_sym).sort")
        out.append("r.permissions = wanted")
        out.append("if r.new_record?")
        out.append("  r.save!")
        out.append("  opl_report(%s, r)" % rb("role " + r.name))
        out.append("elsif r.permissions.map(&:to_sym).sort != before")
        out.append("  r.save!")
        out.append("  puts %s" % rb("role %s: created or changed (permissions)" % r.name))
        out.append("end")

    # 4. Workflows: reset each managed (role, type) pair, then insert.
    _section(out, "Workflows")
    for w in model.workflows:
        pairs = sorted(model.transitions(w.role, w.type))
        out.append("role_rec = Role.find_by!(name: %s, type: 'ProjectRole')" % rb(w.role))
        # A "*" row applies to every known type.
        targets = (
            [t.name for t in model.types]
            if w.type == "*"
            else [w.type]
        )
        for tname in targets:
            out.append("type_rec = Type.find_by!(name: %s)" % rb(tname))
            if w.type == "*":
                type_statuses = by_type[tname].statuses
                pairs = sorted(
                    (a, b) for a in type_statuses for b in type_statuses
                )
            out.append(
                "current = Workflow.where(role_id: role_rec.id, "
                "type_id: type_rec.id)"
                ".order(:old_status_id, :new_status_id)"
                ".pluck(:old_status_id, :new_status_id)"
            )
            out.append("wanted = [")
            for frm, to in pairs:
                out.append(
                    "  [Status.find_by!(name: %s).id, Status.find_by!(name: %s).id],"
                    % (rb(frm), rb(to))
                )
            out.append("].sort")
            out.append("if current.sort != wanted")
            out.append(
                "  Workflow.where(role_id: role_rec.id, type_id: type_rec.id).delete_all"
            )
            out.append("  wanted.each do |old_id, new_id|")
            out.append(
                "    Workflow.create!(role_id: role_rec.id, type_id: type_rec.id, "
                "old_status_id: old_id, new_status_id: new_id)"
            )
            out.append("  end")
            out.append(
                "  puts %s"
                % rb("workflows %s/%s: %d transitions" % (w.role, tname, len(pairs)))
            )
            out.append("end")

    # 5. Work package custom fields: formats, values, multi; is_for_all plus
    # per-type activation. No native admin-only exists on these (T1.1), so
    # Merge OK ships as a plain bool field kept owner-only by the conductor.
    _section(out, "Work package custom fields")
    for f in model.fields:
        out.append(
            "f = WorkPackageCustomField.find_or_initialize_by(name: %s)" % rb(f.name)
        )
        out.append("is_new = f.new_record?")
        out.append("f.field_format = %s if is_new" % rb(f.format))
        out.append("f.is_for_all = true")
        if f.multi:
            out.append("f.multi_value = true")
        if f.format == "list":
            out.append(
                "missing = %s - f.custom_options.map(&:value)"
                % _rb_str_list(f.values)
            )
            out.append("missing.each { |v| f.custom_options.build(value: v) }")
        out.append("if is_new || f.changed? || f.custom_options.any?(&:new_record?)")
        out.append("  f.save!")
        out.append("  opl_report(%s, f)" % rb("field " + f.name))
        out.append("end")
        for tname in f.on:
            out.append("t = Type.find_by!(name: %s)" % rb(tname))
            out.append("unless t.custom_field_ids.include?(f.id)")
            out.append("  t.custom_fields << f")
            out.append(
                "  puts %s" % rb("field %s: activated for type %s" % (f.name, tname))
            )
            out.append("end")

    # 6. Project custom fields, global to every project.
    _section(out, "Project custom fields")
    out.append("section = ProjectCustomFieldSection.first_or_create!(name: 'General')")
    for f in model.project_fields:
        out.append(
            "pf = ProjectCustomField.find_or_initialize_by(name: %s)" % rb(f.name)
        )
        out.append("pf_new = pf.new_record?")
        out.append("pf.project_custom_field_section = section")
        out.append("pf.field_format = %s if pf_new" % rb(f.format))
        out.append("pf.is_for_all = true")
        out.append("if pf_new || pf.changed?")
        out.append("  pf.save!")
        out.append("  opl_report(%s, pf)" % rb("project field " + f.name))
        out.append("end")

    # 7. Status-based progress, confirmed against v17.8.0 source
    # (WorkPackage.status_based_mode? reads exactly this setting).
    _section(out, "Progress mode")
    out.append('if Setting.work_package_done_ratio != "status"')
    out.append('  Setting.work_package_done_ratio = "status"')
    out.append('  puts "setting work_package_done_ratio: created or changed (status)"')
    out.append("end")
    # Exactly one trailing newline (TH.13).
    return "\n".join(out) + "\n"


def _rb_str_list(items):
    return "[" + ", ".join(rb(v) for v in items) + "]"
