# Generated by opl-configure from config/pm-model.toml. Idempotent:
# safe to run on every configure. Prints created/changed records only.

def opl_report(label, record)
  if record.previous_changes.any?
    puts "#{label}: created or changed (#{record.previous_changes.keys.join(", ")})"
  end
end

# --- Statuses ---
s = Status.find_or_initialize_by(name: 'A')
s.assign_attributes(is_closed: false, default_done_ratio: 0, is_default: true)
if s.new_record? || s.changed?
  s.save!
  opl_report('status A', s)
end
s = Status.find_or_initialize_by(name: 'B')
s.assign_attributes(is_closed: true, default_done_ratio: 100, is_default: false)
if s.new_record? || s.changed?
  s.save!
  opl_report('status B', s)
end

# --- Types ---
t = Type.find_or_initialize_by(name: 'T1')
if t.new_record?
  t.save!
  opl_report('type T1', t)
end
Project.find_each do |project|
  pt = ProjectType.find_or_initialize_by(project: project, type: t)
  if pt.new_record?
    pt.save!
    puts "type T1: enabled in project #{project.name}"
  end
end

# --- Roles ---
r = Role.find_or_initialize_by(name: 'Owner', type: 'ProjectRole')
wanted = OpenProject::AccessControl.permissions.reject(&:global?).map(&:name)
raise "no project permissions found in registry" if wanted.empty?
before = r.permissions.map(&:to_sym).sort
r.permissions = wanted
if r.new_record?
  r.save!
  opl_report('role Owner', r)
elsif r.permissions.map(&:to_sym).sort != before
  r.save!
  puts 'role Owner: created or changed (permissions)'
end
r = Role.find_or_initialize_by(name: 'R1', type: 'ProjectRole')
names = ['view_work_packages']
names.each do |pname|
  raise "unknown permission #{pname} in role R1" if OpenProject::AccessControl.permission(pname.to_sym).nil?
end
wanted = names.map(&:to_sym)
before = r.permissions.map(&:to_sym).sort
r.permissions = wanted
if r.new_record?
  r.save!
  opl_report('role R1', r)
elsif r.permissions.map(&:to_sym).sort != before
  r.save!
  puts 'role R1: created or changed (permissions)'
end

# --- Workflows ---
role_rec = Role.find_by!(name: 'Owner', type: 'ProjectRole')
type_rec = Type.find_by!(name: 'T1')
current = Workflow.where(role_id: role_rec.id, type_id: type_rec.id).order(:old_status_id, :new_status_id).pluck(:old_status_id, :new_status_id)
wanted = [
  [Status.find_by!(name: 'A').id, Status.find_by!(name: 'A').id],
  [Status.find_by!(name: 'A').id, Status.find_by!(name: 'B').id],
  [Status.find_by!(name: 'B').id, Status.find_by!(name: 'A').id],
  [Status.find_by!(name: 'B').id, Status.find_by!(name: 'B').id],
].sort
if current.sort != wanted
  Workflow.where(role_id: role_rec.id, type_id: type_rec.id).delete_all
  wanted.each do |old_id, new_id|
    Workflow.create!(role_id: role_rec.id, type_id: type_rec.id, old_status_id: old_id, new_status_id: new_id)
  end
  puts 'workflows Owner/T1: 4 transitions'
end
role_rec = Role.find_by!(name: 'R1', type: 'ProjectRole')
type_rec = Type.find_by!(name: 'T1')
current = Workflow.where(role_id: role_rec.id, type_id: type_rec.id).order(:old_status_id, :new_status_id).pluck(:old_status_id, :new_status_id)
wanted = [
  [Status.find_by!(name: 'A').id, Status.find_by!(name: 'B').id],
].sort
if current.sort != wanted
  Workflow.where(role_id: role_rec.id, type_id: type_rec.id).delete_all
  wanted.each do |old_id, new_id|
    Workflow.create!(role_id: role_rec.id, type_id: type_rec.id, old_status_id: old_id, new_status_id: new_id)
  end
  puts 'workflows R1/T1: 1 transitions'
end

# --- Work package custom fields ---
f = WorkPackageCustomField.find_or_initialize_by(name: 'F1')
is_new = f.new_record?
f.field_format = 'list' if is_new
f.is_for_all = true
missing = ['x', 'y'] - f.custom_options.map(&:value)
missing.each { |v| f.custom_options.build(value: v) }
if is_new || f.changed? || f.custom_options.any?(&:new_record?)
  f.save!
  opl_report('field F1', f)
end
t = Type.find_by!(name: 'T1')
unless t.custom_field_ids.include?(f.id)
  t.custom_fields << f
  puts 'field F1: activated for type T1'
end

# --- Project custom fields ---
section = ProjectCustomFieldSection.first_or_create!(name: 'General')

# --- Progress mode ---
if Setting.work_package_done_ratio != "status"
  Setting.work_package_done_ratio = "status"
  puts "setting work_package_done_ratio: created or changed (status)"
end
